version: '3.8'
services:
  hostel:
    image: node:20-alpine #${FRONTEND_IMAGE:-ghcr.io/hostel_pro-frontend:latest}
    ports:
      - "7011:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./db.json:/app/db.json:rw
    restart: unless-stopped
